#!/bin/bash

BOT_USER_ID=jfelten

#first create an auth token
CONTAINER_ID=`docker run -d jfelten/hook_manager tail -f /dev/null`
docker exec -it $CONTAINER_ID /hook_manager create_authorization --account=$BOT_USER_ID --note="${BOT_USER_ID} - generated by hook manager"
eval $(docker exec -it $CONTAINER_ID cat ./github_cred)
docker kill $CONTAINER_ID

# Store as kubernetes secret
kubectl delete secret hookmanager-cred
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Secret
metadata:
  name: hookmanager-cred
type: Opaque
data:
  auth_id: $(echo "$GITHUB_AUTH_ID" | tr -d '\n\r' | base64)
  auth_token: $(echo "$GITHUB_AUTH_TOKEN" | tr -d '\n\r' | base64)
EOF

